config/routes.rb
Rails.application.routes.draw do
  get '/gossip/:id', to: 'dynamic#gossip'
  get '/author/:id', to: 'dynamic#author', as: 'author'
  get '/welcome', to: 'dynamic#welcome'
  get '/welcome/:id', to: 'dynamic#welcome'
  get '/contact', to: 'static#contact'
  get '/team', to: 'static#team'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :join_table_gossip_tags
    has_many :tags, through: :join_table_gossip_tags
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :join_table_gossip_tags
    has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dynamic_controller.rb
class DynamicController < ApplicationController
  def welcome
    @gossips = Gossip.all
    @users = User.all
  end
  def gossip
    @gossips = Gossip.all
    @users = User.all
  end
  def author
    @gossips = Gossip.all
    @users = User.all
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dynamic_helper.rb
module DynamicHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/dynamic/author.html.erb
<h1>Auteur n°<%=params['id']%></h1>
<h2>Prénom : <%="#{@users[params['id'].to_i].first_name}"%></h2>
<h3>Nom : <%="#{@users[params['id'].to_i].last_name}"%></h3>
<h4>Description : <%="#{@users[params['id'].to_i].description}"%></h4>
<h6>Email : <%="#{@users[params['id'].to_i].email}"%></h6>
<h6>Age : <%="#{@users[params['id'].to_i].age}"%></h6>
<h6>Ville : <%="#{@users[params['id'].to_i].city.name}"%></h6>

app/views/dynamic/gossip.html.erb
<h1>Gossip n°<%=params['id']%></h1>
<h2>Auteur : <%="#{@gossips[params['id'].to_i].user.first_name}"%></h2>
<h3>Titre : <%="#{@gossips[params['id'].to_i].title}"%></h3>
<h4>Contenu : <%="#{@gossips[params['id'].to_i].content}"%></h4>
<h6>Mis à jour : <%="#{@gossips[params['id'].to_i].updated_at}"%></h6>
<br>
<h4><%= link_to "Voir le profil de l'auteur", author_path %></h4>

app/views/dynamic/welcome.html.erb
<h1>Bienvenue <%=params['id']%> !</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>

<div class="row row-cols-1 row-cols-md-3">
  <% @gossips.each do |g|%>
  <div class="col mb-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%="#{g.title} "%></h5>
        <p class="card-text"><%="#{g.user.first_name}"%></p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <div class=container>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <%= link_to "The Gossip Project", welcome_path, class: "navbar-brand"%>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <%= link_to "Team", team_path, class: "nav-link"%>
            </li>
            <li class="nav-item active">
              <%= link_to "Contact", contact_path, class: "nav-link"%>
            </li>
          </ul>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/team/show.html.erb
<h1>Team#show</h1>
<p>Find me in app/views/team/show.html.erb</p>